
export const tabs = {
    main: [
        {
            title: "Schedule and Online Booking",
            description: "",
            list: ["Convenient management of schedules, resources, and conditions.",
                "Appointments can only be made by phone at designated times.",
                "Booking on game day if a moderator is available.",
                "Optional surcharge for online payments.",
                "Automatic billing and penalties for late cancellations.",
                "Customizable online booking widgets."],
            icon: "main/schedule.svg",
            gridColumn: "1 / span 3",
            gridRow: "1 / span 2",
            height: "auto"
        },

        { title: "Email and WhatsApp campaigns",
            description: "Campaign builder with the ability to add custom text, offer additional services for the game, and send photos of participants.",
            icon: "main/email.svg",
            gridColumn: "1 / span 2",
            gridRow: "3 / span 2",
            height: "325px",
        },

        {
            title: "Waivers",
            description: "Agreement signing by each participant before the game.",
            icon: "main/waivers.svg",
            gridColumn: "3 / span 2",
            gridRow: "3 / span 2",
            height: "325px",
        },

        { title: "120+",
            description: "A wide variety of functions in the Escape Navigator CRM system.",
            icon: "main/120+.svg",
            gridColumn: "7 / span 2",
            gridRow: "3 / span 2",
            height: "325px",
        },

        { title: "Custom development",
            description: "If any of your business needs are not met by the current functionality.",
            icon: "main/customDev.svg",
            gridColumn: "5 / span 2",
            gridRow: "3 / span 2",
            height: "325px",
        },

        { title: "Customer Database",
            description: "Segmentation of customers by category with easy export. Trust rating for customers based on behavior and attendance with other companies.",
            icon: "main/customDatabase.svg",
            gridColumn: "4 / span 5",
            gridRow: "2 / span 1",
            height: "auto"
        },

        { title: "Analytics ",
            description: "Data collection through Google Analytics, Tag Manager, Facebook Pixel, and UTM tags. Tracking of affiliate and referral programs.",
            icon: "main/analytics.svg",
            gridColumn: "4 / span 5",
            gridRow: "1 / span 1",
            height: "auto",

        },

    ],


    marketing: [
        { title: "Gift Certificates",
            description: "",
            list: ["Flexible pricing options.",
                "Scheduling the sending date with a greeting via email.",
                "Adding a tracking number to notify the client.",
                "Surcharge for delivery."],
            icon: "marketing/gift.svg",
            gridColumn: "1 / span 2",
            gridRow: "1 / span 5",
            height: "auto",},

        { title: "Additional Services",
            description: "Configuration of prepayment and setting availability by day of the week or by hours, e.g. an actor's participation in a game or hosting a corporate event.",
            icon: "marketing/service.svg",
            gridColumn: "3 / span 2",
            gridRow: "1 / span 4",
            height: "auto",},

        { title: "Retargeting",
            description: "Sending a discount promo code for a repeat booking if a visitor did not complete or canceled their reservation.",
            icon: "marketing/retargeting.svg",
            gridColumn: "5 / span 2",
            gridRow: "1 / span 3",
            height: "auto",},

        { title: "Cross-selling",
            description: "Sending emails after the game with an offer to visit other quests and a personalized promo code for a discount on the next booking.",
            icon: "marketing/cross-selling.svg",
            gridColumn: "1 / span 2",
            gridRow: "6 / span 4",
            height: "auto"},

        { title: "Promo Codes and Promotions",
            description: "Creating promotional offers with flexible settings.",
            icon: "marketing/promo.svg",
            gridColumn: "3 / span 2",
            gridRow: "5 / span 5",
            height: "auto",},

        { title: "Integration with third-party services",
            description: "Over 20 different integrations, including Zapier, allowing for seamless interaction among all your systems.",
            icon: "marketing/integration.svg",
            gridColumn: "5 / span 2",
            gridRow: "4 / span 4",
            height: "auto"},

        { title: "Referral Program",
            description: "",
            icon: "marketing/program.svg",
            gridColumn: "5 / span 2",
            gridRow: "8 / span 2",
            height: "auto",},
    ],


    personal: [
        { title: "Work Schedules",
            description: "Visualization of work schedules, planning of work timetables, and assignments for the game.",
            icon: "personal/work.svg",
            gridColumn: "1 / span 1",
            gridRow: "1 / span 2",
            height: "auto",},

        { title: "Info Board",
            description: "Posting important information on the dashboard for quick notification of all employees.",
            icon: "personal/info.svg",
            gridColumn: "2 / span 2",
            gridRow: "1 / span 1",
            height: "auto",},

        { title: "Payroll Calculation and Incentive System",
            description: "Automatic payroll calculation based on hours worked, games conducted, additional services sold, or souvenirs sold. Accounting for salary and bonus payments.",
            icon: "personal/payroll.svg",
            gridColumn: "4 / span 1",
            gridRow: "1 / span 2",
            height: "auto",
        },

        { title: "Employee Training Center",
            description: "Detailed video guides and a blog with the latest system updates, regular open release presentations, and Zoom meetings for newcomers.",
            icon: "personal/employee.svg",
            gridColumn: "2 / span 2",
            gridRow: "2 / span 1",
            height: "auto",
            },

        { title: "Reports",
            description: "Reports on hours worked, games conducted, and services sold.",
            icon: "personal/report.svg",
            gridColumn: "1 / span 1",
            gridRow: "3 / span 1",
            height: "240px",
        },


        { title: "Action Logging",
            description: "A report of all actions performed by employees in the system.",
            icon: "personal/logging.svg",
            gridColumn: "2 / span 1",
            gridRow: "3 / span 1",
            height: "240px",
        },

        { title: "Tasks for Personnel",
            description: "Assignment of tasks for administrators or technical staff, with the ability to assign tasks for a shift.",
            icon: "personal/tasks.svg",
            gridColumn: "3 / span 2",
            gridRow: "3 / span 1",
            height: "240px",
        },
    ],
};